/*
 * lorawan.h
 *
 *  Created on: Dec 19, 2024
 *      Author: elias
 */

#ifndef DRIVERS_LORAWAN_MODULE_LORAWAN_H_
#define DRIVERS_LORAWAN_MODULE_LORAWAN_H_


//THIS IS A PLACEHOLDER, I'LL RENAME THIS FOR THE MODULE NAME WHEN I CHOOSE ONE :P

#endif /* DRIVERS_LORAWAN_MODULE_LORAWAN_H_ */
